CREATE TABLE PEOPLE(
  PEOPLE_ID NUMBER(11,0) GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1) NOT NULL,
  FIRST_NAME VARCHAR2(200) NOT NULL,
  LAST_NAME VARCHAR2(200) NOT NULL,
  COMPANY_NAME VARCHAR2(200) NOT NULL,
  ADDRESS VARCHAR2(200) NOT NULL,
  CITY VARCHAR2(200) NOT NULL,
  COUNTRY VARCHAR2(200) NOT NULL,
  PEOPLE_STATE VARCHAR2(200) NOT NULL,
  ZIP NUMBER(8,2) NOT NULL,
  PHONE VARCHAR2(200) NOT NULL,
  EMAIL VARCHAR2(200) NOT NULL,
  CONSTRAINT PEOPLE_PK PRIMARY KEY (PEOPLE_ID)
);

COMMIT;

INSERT INTO PEOPLE
(FIRST_NAME, LAST_NAME, COMPANY_NAME, ADDRESS, CITY, COUNTRY, PEOPLE_STATE, ZIP, PHONE, EMAIL)
VALUES(?,?,?,?,?,?,?,?,?,?); 

        